enabled: true
dropdown:
  enabled: true
custom_logo: {  }
footer:
  content: "**Contoso** is a made up organization created by Microsoft to use for product demos .<br>\nThe content and artwork on this website is sample content curated to test the capabilities of this theme<br>\nEmail: [info@example.com](mailto:info@example.com)\nAddress: Contoso, Inc PO Box 12345 Scranton, PA 12345<br>\n\n**IMPORTANT MESSAGE: _The contents of this message are supposed to be important, please read them._**"
  socialMediaIcons:
    -
      icon: 'fa fa-arrows'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
    -
      icon: 'fa fa-step-backward'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
    -
      icon: 'fa fa-align-left'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
    -
      icon: 'fa fa-arrow-circle-left'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
  largeIcons:
    -
      icon: 'fa fa-unlock'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
    -
      icon: 'fa fa-play-circle'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
    -
      icon: 'fa fa-flag-o'
      colorpicker: null
      imageicon: null
      imageurlicon: null
      url: null
  smallicons:
    -
      smallicon:
        icon: 'fa fa-clock-o'
        color: '#ffffff'
        imageurl: null
        header: null
        smalltext: null
        link: null
  largeicons:
    -
      largeicon:
        icon: 'fa fa-lock'
        color: null
        imageurl: null
        header: null
        smalltext: Lock
        link: paclock.com
    -
      largeicon:
        icon: null
        color: null
        imageurl: 'https://i.pinimg.com/474x/53/1b/fc/531bfc96347ec3418a075e5b93760b68.jpg'
        header: null
        smalltext: null
        link: null
    -
      largeicon:
        icon: 'fa fa-list'
        color: null
        imageurl: null
        header: null
        smalltext: null
        link: null
